spring.application.name=ai
# Mudei a porta para 3307 e o nome do banco para gym_db
spring.datasource.url=jdbc:mysql://localhost:3307/gym_db?createDatabaseIfNotExist=true
spring.datasource.username=root
# Mudei a senha para root (a que funcionou no seu terminal)
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração do Groq
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile